[project]
name = "ob1-prob"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.13.2",
    "anthropic>=0.72.0",
    "dotenv>=0.9.9",
    "ipdb>=0.13.13",
    "openai>=2.7.1",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
