import subprocess
from pathlib import Path

def run_cmd(cmd, cwd=None):
    subprocess.run(cmd, cwd=cwd, shell=True, check=True)

def create_worktree(repo_path: Path, branch_name: str) -> Path:
    worktree_dir = repo_path / "worktrees" / branch_name
    run_cmd(f"git fetch origin main", cwd=repo_path)
    run_cmd(f"git worktree add {worktree_dir} origin/main", cwd=repo_path)
    run_cmd(f"git -C {worktree_dir} checkout -b {branch_name}", cwd=repo_path)
    return worktree_dir

def commit_push_pr(repo_path: Path, worktree_path: Path, branch_name: str, prompt: str, agent: str):
    run_cmd(f"git -C {worktree_path} add -A")
    run_cmd(f'git -C {worktree_path} commit -m "feat({agent}): {prompt}"')
    run_cmd(f"git -C {worktree_path} push -u origin {branch_name}")
    run_cmd(
        f'gh pr create --head {branch_name} --base main '
        f'--title "feat({agent}): {prompt}" '
        f'--body "Generated by {agent} for task: {prompt}" '
        f'--label agent:{agent}',
        cwd=repo_path,
    )
