import asyncio
import os
from datetime import datetime
from pathlib import Path
from ob1.git_utils import create_worktree, commit_push_pr
from ob1.agent_base import get_agent_class
from ob1.utils.logging_utils import log
from ob1.github_api import (
    create_branch, commit_files_batch, create_pr, get_default_branch, set_repo_context
)
from dotenv import load_dotenv

# Load .env file automatically at runtime
load_dotenv()


async def run_agent(agent_name, prompt, repo_path: Path):
    run_id = datetime.now().strftime("%Y%m%d%H%M%S")
    branch_name = f"feat/{agent_name}-{run_id}"
    worktree_path = create_worktree(repo_path, branch_name)

    AgentCls = get_agent_class(agent_name)
    agent = AgentCls(agent_name)

    log(f"[{agent_name}] Starting work...")
    await agent.run(worktree_path, prompt)

    log(f"[{agent_name}] Committing & creating PR...")
    commit_push_pr(repo_path, worktree_path, branch_name, prompt, agent_name)
    log(f"[{agent_name}] ✅ Done!")


async def run_agent_remote(agent_name: str, prompt: str):
    # Make sure env creds are set
    gh_owner = os.getenv("GH_OWNER")
    gh_repo = os.getenv("GH_REPO")
    if not gh_owner or not gh_repo:
        raise RuntimeError("Missing GH_OWNER or GH_REPO in environment")

    set_repo_context(gh_owner, gh_repo)

    run_id = datetime.now().strftime("%Y%m%d%H%M%S")
    task_slug = "login-page"
    branch = f"feat/{task_slug}-{agent_name}-{run_id}"
    base = get_default_branch()

    create_branch(branch, base)

    AgentCls = get_agent_class(agent_name)
    agent = AgentCls(agent_name)
    files = await agent.generate_files(prompt)  # returns {path: content}

    message = f"feat({agent_name}): {prompt}"
    commit_files_batch(branch, files, message)

    pr_url = create_pr(
        title=message,
        head_branch=branch,
        base_branch=base,
        body=f"Generated by {agent_name} for task: {prompt}",
    )
    log(f"[{agent_name}] ✅ PR created: {pr_url}")


async def run_orchestration(prompt: str, agent_names: list[str],
                            remote: bool = False, owner=None, repo=None):
    gh_owner = owner or os.getenv("GH_OWNER")
    gh_repo = repo or os.getenv("GH_REPO")
    if not gh_owner or not gh_repo:
        raise RuntimeError("Missing GH_OWNER or GH_REPO in environment")

    set_repo_context(gh_owner, gh_repo)

    if remote:
        tasks = [run_agent_remote(a, prompt) for a in agent_names]
    else:
        tasks = [run_agent(a, prompt, Path(".")) for a in agent_names]

    await asyncio.gather(*tasks)


